# vim:fileencoding=utf-8:foldmethod=marker

# BEGIN_KITTY_THEME
# shadotheme
include current-theme.conf
font_family JetBrainsMono Nerd Font
font_size 12
cursor_shape beam
cursor_blink_interval 0.5
initial_window_width  1100
initial_window_height 700
confirm_os_window_close 0
background_opacity 0.85

